sources:
  - name: Authors
    handler:
      graphql:
        endpoint: ./src/mock-schema/mock-schema.graphql

transforms:
  - mock:
      if: true
      initializeStore: ./src/resolvers/authors.query.ts#initializeStore
      mocks:
        - apply: Query.author
          custom: ./src/resolvers/authors.query.ts#author

require:
  - ts-node/register/transpile-only

serve:
  port: 4000
  cors: { origin: http://localhost:3000 }
  playground: true
  exampleQuery: |
    # queries
    query Authors {
      authors {
        id
        name
        type {
          id
          name
          version
        }
        created_at
        registration_number
      }
    }

    query Author($id: ID!) {
      author(id: $id) {
        __typename
        id
        name
        type{
          id
          name
          version
        }
        created_at
        registration_number
      }
    }

    query AuthorPerhaps($id: ID!) {
      authorPerhaps(id: $id) {
        __typename
        ... on ExistingAuthor{
          id
          name
          type{
            id
            name
            version
          }
          created_at
          registration_number
        }
        ... on AuthorDoesNotExistError{
          message
        }
      }
    }
